DELETE https://crudcrud.com/api/cbb0ae2e39f9429ea650bab05298a330/student/66e745e4fe837603e816c280
Accept: application/json
###

GET https://crudcrud.com/api/cbb0ae2e39f9429ea650bab05298a330/student/66e745e4fe837603e816c280
Accept: application/json

###
POST https://crudcrud.com/api/cbb0ae2e39f9429ea650bab05298a330/student
Content-Type: application/json

{
  "name": "Иван",
  "grade": 4
}